"""empty message

Revision ID: 0b97750fcf68
Revises: 
Create Date: 2020-04-25 15:38:37.412407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b97750fcf68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_types',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('host_id', sa.String(length=255), nullable=True),
    sa.Column('game_type_id', sa.String(length=30), nullable=True),
    sa.Column('num_of_questions', sa.Integer(), nullable=True),
    sa.Column('live_game', sa.Integer(), nullable=True),
    sa.Column('game_created', sa.DateTime(), nullable=True),
    sa.Column('join_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hosts',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('salt', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('game_id', sa.String(length=255), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('game_id', sa.String(length=255), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('answer', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('players')
    op.drop_table('hosts')
    op.drop_table('games')
    op.drop_table('game_types')
    # ### end Alembic commands ###
